ops:
  carbon_cpu_enriched_sequences:
    config:
      validation_level: dev
      streaming: true
      batch_size: 100
      rows_per_shard: 100
      compression: zstd
      output_dir: ".dagster_hf_storage/test_100"
      enable_progress: true